GymManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
   

    path('pagedetail/<int:id>/', views.page_detail, name='pagedetail'),
    path('faq/', views.faq, name='faq'),
    path('enquiry/', views.enquiry, name='enquiry'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallerydetail/<int:id>', views.gallery_detail, name='gallerydetail'),
    path('subscriptions/', views.subscription, name="subscription"),
    path('checkout/<int:sub_id>', views.checkout, name='checkout'),

    path('checkout_session/<int:sub_id>', views.checkout_session, name='checkout_session'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('payment_cancel/', views.payment_cancel, name='payment_cancel'),





]

base/models.py
from django.db import models
from django.utils.safestring import mark_safe

from django.contrib.auth.models import User

# Create your models here


class Banners(models.Model):
    image = models.ImageField(upload_to='banners/')
    alt_text = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.alt_text}"
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="100"/>' % (self.image.url))
                

class Service(models.Model):
    title = models.CharField(max_length=50)
    details = models.TextField()
    image = models.ImageField(upload_to='services/', null=True)

    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="100"/>' % (self.image.url))
    

class Page(models.Model):
    title = models.CharField(max_length=50)
    details = models.TextField()

    def __str__(self):
        return self.title
    
class faq_list(models.Model):
    question=models.CharField(max_length=200)
    answer=models.TextField()

    def __str__(self):
        return self.question
    

class Enquiry(models.Model):
    full_name = models.CharField(max_length=150)
    email = models.EmailField()
    detail = models.TextField()
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name
    
class Gallery(models.Model):
    title = models.CharField(max_length=100)
    detail = models.TextField()
    image = models.ImageField(upload_to='gallery/', null=True)

    def __str__(self):
        return self.title
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="100"/>' % (self.image.url))
    
class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, null=True)
    alt_text = models.CharField(max_length=100)
    image = models.ImageField(upload_to='gallery_image/', null=True)

    def __str__(self):
        return self.alt_text
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="100"/>' % (self.image.url))
    

class Subscription(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    highlight_status = models.BooleanField(default=False)
    max_num = models.IntegerField(null=True)
    availiable = models.IntegerField(null=True)

    def __str__(self):
        return self.title
    
class SubscriptionFeature(models.Model):
    subscription = models.ManyToManyField(Subscription)
    title = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.title}"

class discount(models.Model):
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE, null=True)
    total_months = models.IntegerField()
    total_discount = models.IntegerField()

    def __str__(self):
        return str(self.total_months)


class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=15)
    address = models.TextField()
    image = models.ImageField(upload_to='subs/')

    def __str__(self):
        return str(self.user)
    
    def image_tag(self):
        if self.image:
            return mark_safe('<img src="%s" width="100"/>' % (self.image.url))
        else:
            return 'no-image'

from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=User)
def create_subscriber(sender, instance, created, **kwargs):
    if created:
        Subscriber.objects.create(user=instance)


class SubscribedUsers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    plan = models.ForeignKey(Subscription, on_delete=models.CASCADE, null=True)
    price = models.CharField(max_length=50)

class Trainer(models.Model):
    full_name =models.CharField(max_length=100)
    mobile_number = models.CharField(max_length=15)
    address = models.TextField()
    is_active = models.BooleanField(default=False)
    detail = models.TextField()
    image = models.ImageField(upload_to='trainers/')

    def __str__(self):
        return str(self.full_name)
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="100"/>' % (self.image.url))
    

base/forms.py
from django import forms
from . import models

class EnquiryForm(forms.ModelForm):
    class Meta:
        model =models.Enquiry
        exclude = ('time',) 

base/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import EnquiryForm

#from django.db.models import Count
#from django.contrib.auth import authenticate

import stripe
from dotenv import load_dotenv


# Create your views here.

def home(request):
    banners = Banners.objects.all()
    services = Service.objects.all()[:3]
    gimages = GalleryImage.objects.all().order_by('-id')[:9]
    context = {'banners':banners, 'services':services, 'gimages':gimages}
    return render(request, 'base/home.html', context)

def page_detail(request, id):
    page = Page.objects.get(id=id)
    context = {'page':page}
    return render(request, 'base/page.html', context)

def faq(request):
    faqs = faq_list.objects.all()
    context = {'faqs':faqs}
    return render(request, 'base/faq.html', context)

def enquiry(request):
    mesg=''
    form = EnquiryForm()
    if request.method == 'POST':
        form=EnquiryForm(request.POST)
        if form.is_valid():
            form.save()
            mesg = 'Data has been saved.'
    
    form = EnquiryForm()
    context = {'form':form, 'mesg':mesg}
    return render(request, 'base/enquiry.html', context)

    
    # context= {'form':form}
    # return render(request, 'base/enquiry.html', context)


def gallery(request):
    gallerys = Gallery.objects.all().order_by('-id')
    context = {'gallerys': gallerys}
    return render(request, 'base/gallery.html', context)

def gallery_detail(request, id):
    gallery = Gallery.objects.get(id=id)
    gallery_img = GalleryImage.objects.filter(gallery=gallery).order_by('-id')
    context = {'gallery_img':gallery_img, 'gallery':gallery}
    return render(request, 'base/detailgallery.html', context)

def subscription(request):
    subscription = Subscription.objects.all().order_by('price')
    distinct_features = SubscriptionFeature.objects.all()
    context = {'subscription':subscription, 'distinct_features': distinct_features}
    return render(request, 'base/pricing.html', context)


def checkout(request, sub_id):
    SubscriptionDetail = Subscription.objects.get(pk=sub_id)
    sub_feature = SubscriptionFeature.objects.all()
    discounts = discount.objects.all()
    context = {'subscriptiondetail': SubscriptionDetail, 'sub_feature': sub_feature, 'discounts':discounts}
    return render(request, 'base/checkout.html', context)

import os
def configure():
    load_dotenv()

configure()
stripe.api_key = os.getenv('stripe_key')
def checkout_session(request, sub_id ):
    plan = Subscription.objects.get(pk=sub_id)
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price_data': {
                'currency': 'npr',
                'product_data': {
                    'name': plan.title,
                },
                'unit_amount': plan.price*100,
            },
            'quantity':1,
        }],
        mode='payment',
        success_url = 'http://127.0.0.1:8000/payment_success?session_id={CHECKOUT_SESSION_ID}',
        cancel_url='http://127.0.0.1:8000/payment_cancel',
        client_reference_id = sub_id
    )
    return redirect(session.url, code=303)


from django.core.mail import EmailMessage
from django.template.loader import get_template

def payment_success(request):
    session = stripe.checkout.Session.retrieve(request.GET['session_id'])
    plan_id = session.client_reference_id
    plan = Subscription.objects.get(pk=plan_id)
    user = request.user 
    SubscribedUsers.objects.create(
        plan = plan,
        user = user,
        price = plan.price
    )
    subject = 'Order Email'
    html_content = get_template('base/ordermail.html').render({'title':plan.title})
    from_email = 'manoramsubedi7@gmail.com'
    msg = EmailMessage(subject, html_content, from_email, ['nunam933@gmail.com'])
    msg.content_subtype = "html"  # Main content is now text/html
    msg.send()

    return render(request, 'base/success.html')

def payment_cancel(request):
    return render(request, 'base/cancel.html')

base/templates/base/cancel.html
{% extends "main.html" %}
{% load static %}

{% block content %}
    <section class="container my-4">
        <h3>Something went wrong</h3>
        
    </section>

{% endblock %}

base/templates/base/checkout.html
{% extends "main.html" %}
{% load static %}

{% block content %}

<section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
        <table class="table table-bordered">
            <thead class="table-warning">
                <tr>
                    <th>Plan</th>
                    <th>Plan Detail</th>
                    <th>Payment For</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <table class="table-bordered table">
                            <tr>
                                <th>Name</th>
                                <td>{{subscriptiondetail.title}}</td>
                            </tr>
                            <tr>
                                <th>Price</th>
                                <td>Rs.{{subscriptiondetail.price}}</td>
                            </tr>
                            <tr>
                                <th>Max Member</th>
                                <td>{{subscriptiondetail.max_num}}</td>
                            </tr>
                            <tr>
                                <th>Availiable Seats</th>
                                <td>{{subscriptiondetail.availiable}}</td>
                            </tr>
 
                        </table>
                    </td>
                    <td>
                        <ul class="list-unstyled">
                        {% for detail in sub_feature %}
                          <li>{{detail.title}}</li>
                        {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <table class="table table-bordered">
                            {% for discount in discounts %}
                           
                            <tr>
                                <td><input data-planprice="{{subscriptiondetail.price}}" data-discount="{{discount.total_discount}}" type="radio" id="validity{{discount.id}}" name="validity" class="select-validity" value="{{discount.total_months}}" /></td>
                                <th><label for="validity{{discount.id}}">{{discount.total_months}} Month</label></th>
                                <td>{{discount.total_discount}}%</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </td>
                </tr>
            </tbody>
            <tfoot class="table-info">
                <tr>
                    <td></td>
                    <th>Total Amount</th>
                    <td><b>Rs.<span class="totalAmount">{{subscriptiondetail.price}}</span></b></td>
                </tr>
                <tr>
                    <form method="post" action="{% url 'checkout_session' subscriptiondetail.id %}">
                        {% csrf_token %}
                    <td colspan="2"></td>
                    <td><input type="submit" value="Proceed to Payment" class="btn btn-primary" /></td>
                    </form>
                </tr>
            </tfoot>
        </table>
</section>
<!-- End -->


<script type="text/javascript">
$(document).ready(function(){
$(".select-validity").on('click',function(){
    var _planPrice=$(this).attr('data-planprice');
    var _planDisc=$(this).attr('data-discount');
    var _planValid=$(this).val();
    var _totalPrice=_planPrice*_planValid;
    if(_planDisc>0){
        var _discountedPrice=_totalPrice*_planDisc/100;
        _discountedPrice=_totalPrice-_discountedPrice;
    }else{
        var _discountedPrice=_totalPrice;
    }
    $(".totalAmount").text(_discountedPrice);
});
});
</script>

{% endblock %}

base/templates/base/detailgallery.html
{% extends "main.html" %}


{% block content %}
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">{{gallery.title}} Images</h1>
        <div class="row">
        {% for gimg in gallery_img %}
            <div class="col-md-4 mb-4">
                <div class="card">
                <img src="{{gimg.image.url}}" class="card-img-top" alt="{{gimg.alt_text}}">
                
                </div>
        {% endfor %}
            </div>
    </section>
{% endblock %}

base/templates/base/enquiry.html
{% extends "main.html" %}
{% load static %}

{% block content %}
<!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'enquiry.jpg' %}" class="img-fluid" /> 
            </div>
            <div class="col-md-6">
                {% if mesg %}
                <p class="text-success">{{mesg}}</p>
                {% endif %}
                <form method="POST" action={% url 'enquiry' %}>
                    {% csrf_token %}
                    <table class="table table-bordered">
                        {{form.as_table}}
                        <tr>
                            <td colspan="2">
                                <input type="submit" class="btn btn-primary" />
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

base/templates/base/faq.html
{% extends "main.html" %}
{% load static %}

{% block content %}
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
        <div class="accordion" id="accordionExample">
        {% for faq in faqs %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
                    {{faq.question}}
                </button>
                </h2>
                <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                       {{faq.answer}}
                </div>
            </div>
        {% endfor %}
        </div>
    </section>

{% endblock %}

base/templates/base/gallery.html
{% extends "main.html" %}


{% block content %}
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Gallery</h1>
        <div class="row">
        {% for gallery in gallerys %}
            <div class="col-md-4 mb-4">
                <div class="card">
                <img src="{{gallery.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{gallery.title}}</h5>
                    <p class="card-text">{{gallery.detail}}</p>
                    <a href="{% url 'gallerydetail' gallery.id %}" class="btn btn-primary">View All</a>
                </div>
                </div>
        {% endfor %}
            </div>
    </section>
{% endblock %}

base/templates/base/home.html
{% extends "main.html" %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
        <p>Welcome @{{ user.username }}</p>
{% endif %}
    <!-- banner Start -->
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner active">
      {% for banner in banners %}
        <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
          <img src="{{banner.image.url}}" class="d-block w-100" alt="{{banner.alt_text}}">
        </div>
      {% endfor %}
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <!-- End Banner -->
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading">Services</h1>
        <div class="row">
          {% for service in services %}
            <div class="col-md-4">
              
                <div class="card">
                  <img src="{{service.image.url}}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h3 class="card-title">{{service.title}}</h3>
                    <p class="card-text">{{service.details|truncatewords:9}}</p> <!--truncatechars:9-->
                    <a href="service.php" class="btn btn-primary">Read More</a>
                  </div>
                </div>
              
            </div>
          {% endfor %}
        </div>
    </section>
    <!-- End -->

    <!-- Testimonials -->
    <section class="container-fluid bg-light py-4 mt-5 border-top border-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                        <h1 class="mb-4 section-heading">About Us</h1>
                        <p class="lh-base">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1550s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        <p><a href="{% url 'pagedetail' 1 %}" class="btn btn-info text-white">Read More</a></p>
                </div>
                <div class="col-md-6 offset-1">
                        <h1 class="mb-4 section-heading">Gallery <a href="#" class="float-end btn btn-info text-white mt-2">View All</a></h1>
                        <div class="gallery">
                          {% for gimgs in gimages %}
                            <a href="{{gimgs.image.url}}" data-lightbox="gallery"> <img src="{{gimgs.image.url}}" width="155" class="img-thumbnail" alt="{{gimgs.alt_text}}"></a>
                          {% endfor %}
                        </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Testimonials -->

<script type="text/javascript" src="{% static 'lightbox2-2.11.3/dist/js/lightbox.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'lightbox2-2.11.3/dist/css/lightbox.min.css' %}" />
{% endblock %}

base/templates/base/ordermail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Email</title>
</head>
<body>
    {{title}}
</body>
</html>

base/templates/base/page.html
{% extends "main.html" %}
{% load static %}

{% block content %}

    <!-- Page -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">{{page.title}}</h1>
        <p>{{page.detail}}</p>
    </section>
    <!-- End -->

    

{% endblock %}

base/templates/base/pricing.html
{% extends "main.html" %}
{% load static %}

{% block content %}

<section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>

  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">

        {% for plan in subscription %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm {% if plan.highlight_status %} border-primary {% endif %}">
                <!-- <div class="card mb-4 rounded-3 shadow-sm"> -->
                {% if plan.highlight_status %}
                <div class="card-header py-3 text-white bg-primary border-primary">
                {% else %}
                    <div class="card-header py-3">
                {% endif %}
                    <h4 class="my-0 fw-normal">{{plan.title}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">Rs.{{plan.price}}<small class="text-muted fw-light">/mo</small></h1>
                    <h4><p class="text-success">{{plan.max_num}} Seats Availiable.</p></h4>
                    <ul class="list-unstyled mt-3 mb-4">
                        {% for feature in plan.subscriptionfeature_set.all %}
                            <li>{{feature.title}}</li>    
                        {% endfor %}      
                    </ul>
                  {% if request.user.is_authenticated %}
                    <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
                  {% else %}
                    <a href="{% url 'login' %}" class="w-100 btn btn-lg btn-outline-primary">Login</a>
                  {% endif %}
                </div>
                
                </div>
            </div>
      
            {% endfor %}
        </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            {% for plan in subscription %}
                <th style="width: 22%;">{{plan.title}}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
        {% for feature in distinct_features %}
          <tr>
            <th scope="row" class="text-start">{{feature.title}}</th>
            {% for plan in subscription %}
                <td>
                  {% if plan in feature.subscription.all %}
                    <i class="bi bi-check"></i>
                    {% else %}
                    <i class="bi bi-x text-danger"></i>
                    {% endif %}
                </td>
                    
            {% endfor %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
</section>

{% endblock %}

base/templates/base/success.html
{% extends "main.html" %}
{% load static %}

{% block content %}
    <section class="container my-4">
        <h3>Thanks for your payment</h3>
        
    </section>

{% endblock %}